Controllers/UserRolesManagerController.cs
using Aprender.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebApplicationIdentity.Controllers
{
    [Authorize(Roles = "Admin, Secretario")]
    public class UserRolesManagerController : Controller
    {
        private readonly UserManager<Usuario> userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        public UserRolesManagerController(UserManager<Usuario> _userManager,
        RoleManager<IdentityRole> _roleManager)
        {
            roleManager = _roleManager;
            userManager = _userManager;
        }
        public async Task<IActionResult> Index()
        {
            var users = await userManager.Users.ToListAsync();
            var userRoles = new List<UserRoles>();
            foreach (Usuario user in users)
            {
                var thisViewModel = new UserRoles();
                thisViewModel.UserId = user.Id;
                thisViewModel.Email = user.Email;
                thisViewModel.Nombre = user.Nombre;
                thisViewModel.Apellido = user.Apellido;
                thisViewModel.Roles = await GetUserRoles(user);
                userRoles.Add(thisViewModel);
            }
            return View(userRoles);
        }
        private async Task<List<string>> GetUserRoles(Usuario user)
        {
            return new List<string>(await userManager.GetRolesAsync(user));
        }
        public async Task<IActionResult> Manage(string userId)
        {
            ViewBag.userId = userId;
            var user = await userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            ViewBag.UserName = user.UserName;
            var model = new List<ManagerUserRoles>();
            foreach (var role in roleManager.Roles)
            {
                var userRolesViewModel = new ManagerUserRoles
                {
                    RoleId = role.Id,
                    RoleName = role.Name

                };
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                model.Add(userRolesViewModel);
            }
            return View(model);
        }
        [Authorize(Roles = "Admin, Secretario")]
        [HttpPost]
        public async Task<IActionResult> Manage(List<ManagerUserRoles> model, string userId)
        {
            var user = await userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View();
            }
            var roles = await userManager.GetRolesAsync(user);
            var result = await userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            result = await userManager.AddToRolesAsync(user, model.Where(x =>
            x.Selected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/UserRolesManager/Index.cshtml
@model List<UserRoles>
@{
    ViewData["Title"] = "Index";
}

<h1>Roles por usuario</h1>

<table id="table" class="table table-hover table-borderless table-striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Email</th>
            <th>Roles</th>
            @if (User.IsInRole("Admin"))
            {
               <th>Action</th> 
            }            
        </tr>
    </thead>
    <tbody>
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Nombre</td>
            <td>@user.Apellido</td>
            <td>@user.Email</td>
            <td>@string.Join(" , ", user.Roles.ToList())</td>            
            @if (User.IsInRole("Admin"))
            {
                <td>
                    <a class="btn btn-primary" asp-controller="UserRolesManager" asp-action="Manage" asp-route-userId="@user.UserId">Administrar roles</a>
                </td>
            }
        </tr>
    }
    </tbody>
</table>

Views/UserRolesManager/Manage.cshtml
@using Aprender.Models;
@model List<ManagerUserRoles>
@{
    ViewData["Title"] = "Manage";
}
<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Manage User Roles</h2>
            Add/Remove Roles for User / @ViewBag.UserName.
        </div>
    <div class="card-body">
        @for (int i = 0; i < Model.Count; i++)
        {
            <div class="form-check m-1">
                <input type="hidden" asp-for="@Model[i].RoleId" />
                <input type="hidden" asp-for="@Model[i].RoleName" />
                <input asp-for="@Model[i].Selected" class="form-check-input" />
                <label class="form-check-label" asp-for="@Model[i].Selected">
                    @Model[i].RoleName
                </label>
            </div>
        }
        <div asp-validation-summary="All" class="text-danger"></div>
    </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary" style="width:auto" />
            <a asp-action="Edit" asp-route-id="@ViewBag.userId" class="btn btn-primary" style="width:auto">Cancel</a>
        </div>
    </div>
</form>